### ISSUE TITLE
Request : make the project Android-Studio 2.0.x friendly 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [renaudcerrato/FloatingSearchView#1]
to import.

**Comment by renaudcerrato** [comment]
What do you mean?

**Comment by AndroidDeveloperLB** [comment]
currently when i try to import the project, it fails, as it shows this:

![untitled20160104012322](https://cloud.githubusercontent.com/assets/5357526/12081442/cb8cef56-b281-11e5-9c1c-045a56309d58.png)

**Comment by renaudcerrato** [comment]
I'm developing on Android Studio, and IMO there's nothing more to do on my side. You're using an AS preview BTW. 

What steps are you doing to import it?

**Comment by AndroidDeveloperLB** [comment]
The usual:
VCS->checkout...->git

**Comment by renaudcerrato** [comment]
1/ clone the project manually using git clone 
2/ File -> Import, choose the root directory.

**Comment by AndroidDeveloperLB** [comment]
This is not Android-Studio friendly way to open a project. it's not even open a project. it's import.
In standard way to do so, you choose "file-open" and not "file->import". and, like most of the repos here on github, it should be possible to do what I did originally.
You should update the repo to include the project file as they are after the import is done and working.

**Comment by AndroidDeveloperLB** [comment]
also, btw, running the sample (which works well), I suggest that pressing back would not close the activity if the icon has changed to the arrow, but instead change back to a magnifying glass first

**Comment by renaudcerrato** [comment]
@AndroidDeveloperLB : IDE project files shouldn't be commited to a VCS, they just pollute the repo. They're IDE specifics - and the project have nothing to do with any IDE, this is a gradle project.  Android Studio allows you to properly import Gradle projects.

**Comment by AndroidDeveloperLB** [comment]
Android Studio also allows me to easily import github repos without the need of external tool, and run them just fine, but here it can't.

**Comment by renaudcerrato** [comment]
You're using a preview version of Android Studio. If you think there's a
bug, please report to the Android tools team.

**Comment by AndroidDeveloperLB** [comment]
Seems it doesn't occur on 1.5.1 version of the IDE. Odd. Do you suggest to write about it here:
https://code.google.com/p/android/issues/entry
?

**Comment by renaudcerrato** [comment]
Yep, choose the tools section.

**Comment by AndroidDeveloperLB** [comment]
Sure the tools? Isn't it related to the IDE? All the Android Studio versions should use the same sdk tools that I've installed, no?

**Comment by renaudcerrato** [comment]
Do they have an IDE section? If so, yes.
