### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by dvirguttman** [renaudcerrato/FloatingSearchView#12]
Hi,

I spent all the day try resolve it without any success..

I'm developing on Windows 8 machine with Android Studio, try to use your library in my application.

Adding the following lines:

root gradle file:
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

app gradle file:

dependencies {
...
compile 'com.github.renaudcerrato:FloatingSearchView:1.0.0'
}

Cause the following error:
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not resolve com.github.renaudcerrato:FloatingSearchView:1.0.0.
  >  Required by:
  >      CashBackApp:app:unspecified
  > Could not resolve com.github.renaudcerrato:FloatingSearchView:1.0.0.
  >      > Could not get resource 'https://jitpack.io/com/github/renaudcerrato/FloatingSearchView/1.0.0/FloatingSearchView-1.0.0.pom'.
  >         > Could not GET 'https://jitpack.io/com/github/renaudcerrato/FloatingSearchView/1.0.0/FloatingSearchView-1.0.0.pom'.
  >            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

No matter what I tried - nothing fix it:
1. Update Android Studio - 2.1(latest)
2. Update gradle - 2.12(latest)
3. Update Java 1.8.77(latest)
   4.Download jitpack certificate, generate keytool and run Android Studio with JVM params:-Djavax.net.ssl.keyStore=XXX

Did you face this problem? Can you help with that?

I will be very thankful!

Thanks

**Comment by renaudcerrato** [comment]
Are you using android gradle plugin 2.0.0?

**Comment by dvirguttman** [comment]
Currently yes.
But it it didn't work also for 1.5.0

**Comment by renaudcerrato** [comment]
As a dirty workaround, did you tried to use http instead of https on
jitpack maven url?

**Comment by dvirguttman** [comment]
Very strange..but same:

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > Could not resolve all dependencies for configuration ':app:_debugCompile'.
  > Could not resolve com.github.renaudcerrato:FloatingSearchView:1.0.0.
  >  Required by:
  >      CashBackApp:app:unspecified
  > Could not resolve com.github.renaudcerrato:FloatingSearchView:1.0.0.
  >      > Could not get resource 'http://jitpack.io/com/github/renaudcerrato/FloatingSearchView/1.0.0/FloatingSearchView-1.0.0.pom'.
  >         > Could not GET 'http://jitpack.io/com/github/renaudcerrato/FloatingSearchView/1.0.0/FloatingSearchView-1.0.0.pom'.
  >            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.92 secs

**Comment by renaudcerrato** [comment]
Had a similar error a few days ago, maybe that could help :

https://github.com/jitpack/jitpack.io/issues/514#issuecomment-207736706

**Comment by dvirguttman** [comment]
Thanks,

But it was the problem before upgrade to 2.12..
After upgrade I stuck with the ValidatorException.

**Comment by renaudcerrato** [comment]
Does it only occurs on jitpack dependencies? If so, post an issue to
jitpack.io?

**Comment by dvirguttman** [comment]
It was problem, with my internet provider..
Many thanks.
