### ISSUE TITLE
How to use this FloatingSearchView with ArrayList<Strting> ?

### ISSUE THREAD

**Issue by avtarsingh1122** [renaudcerrato/FloatingSearchView#13]
I tried using the sample app of this FloatingSearchView and it was working fine. What I want is to use this FloatingSearchView with ArrayList<String>    How can I do it ? Is it possible or not ? Please provide a sample code if possible. Thank You.

**Comment by renaudcerrato** [comment]
GitHub bug tracker are for issues, not for seeking help about Android. Please ask on StackOverflow.
