### ISSUE TITLE
search being called twice

### ISSUE THREAD

**Issue by Julienpraad** [renaudcerrato/FloatingSearchView#14]
Hello
public void onSearchAction(CharSequence text) is being called twice when the search of the keyboard is clicked 

how can we stop that ? 

Thank you

**Comment by renaudcerrato** [comment]
Hi Julien,

Can you produce a small test unit to reproduce that issue?

**Comment by Julienpraad** [comment]
Hey yes of course.. just remove everything inside of it and replace it with a simple toast .. or an intent to a new activity.. if u used a toast for example it will be displayed twice in a row .. or a new activity is created twice.. so when u press back inside of it you have to do it twice in order to go back

**Comment by renaudcerrato** [comment]
A test unit would be fine, really =)

**Comment by Julienpraad** [comment]
I am new to github maybe I misunderstood what is a test unit

**Comment by renaudcerrato** [comment]
An [unit test](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html) is a small piece of code, usually run from the command line, which can only output "SUCCESS" or "FALSE". In case of issues like this, it will simply give me a quick way to confirm your bug and easily confirm it by simply running that unit test.

**Comment by AfzalivE** [comment]
You can call `mSearchView.setActivated(false)` in `onSearchAction(CharSequence text)` to avoid this. That's how the sample does it too.

**Comment by Julienpraad** [comment]
Thanks a lot for the reply and sorry for my late one. I did it in another way however I changed it now to your simple way
