### ISSUE TITLE
Is it possible to locate it over the toolbar?

### ISSUE THREAD

**Issue by Bubumuk** [renaudcerrato/FloatingSearchView#5]
Is it possible to put it like a persistent search bar? above the toolbar.

I can't figure it out how to do it.

**Comment by renaudcerrato** [comment]
Did you looked at the sample?

**Comment by Bubumuk** [comment]
yeah.
I'm trying to achieve this:

![components_tabs_usage_mobile2](https://cloud.githubusercontent.com/assets/4107434/12877901/e3271544-cdd7-11e5-9c8a-61d6ffe1d6de.png)

**Comment by renaudcerrato** [comment]
There's a trick: do not put the persistent search view inside the toolbar.
The search view is above everything.

**Comment by Bubumuk** [comment]
Ok, I'll try that out. thanks.
