### ISSUE TITLE
Search view position

### ISSUE THREAD

**Issue by DiligentMe** [renaudcerrato/FloatingSearchView#7]
How can we put the search view in the bottom? is it possible?

**Comment by renaudcerrato** [comment]
Nope, this is not possible, sorry.

**Comment by DiligentMe** [comment]
Its a good useful library. Your demo app works perfectly .But following the steps for adding it in Android studio doesn't work. Do I need to use library to build on my own system!? Many layout errors I get. What minimum to do to use it with sqlite database but not online search!? Any example link will also be helpful.

**Comment by DiligentMe** [comment]
Its a good useful library. Your demo app works perfectly .But following the steps for adding it in Android studio doesn't work. Do I need to use library to build on my own system!? Many layout errors I get. What minimum to do to use it with sqlite database but not online search!? Any example link will also be helpful.
