### ISSUE TITLE
Not working following the steps given here

### ISSUE THREAD

**Issue by DiligentMe** [renaudcerrato/FloatingSearchView#8]
Its a good useful library. Your demo app works perfectly .But following the steps for adding it in Android studio doesn't work. Do I need to use library to build on my own system!? Many layout errors I get. What minimum to do to use it with sqlite database but not online search!? Any example link will also be helpful.

**Comment by renaudcerrato** [comment]
Importing a gradle project from Android Studio should be straightforward and github issues are not a place for that kind of discussion. Try StackOverflow or google for it.
