### ISSUE TITLE
Hamburger toggle misbehaviour

### ISSUE THREAD

**Issue by tuanna-hsp** [renaudcerrato/FloatingSearchView#9]
The toggle does not finish animation or not doing animation at all (when i build release with minify enable). It happened when i build project on some PC but not some others.
![screenshot_2016-03-08-17-30-41-260](https://cloud.githubusercontent.com/assets/14136939/13599117/0304fcda-e554-11e5-8ed8-6ceb95fbfb79.jpeg)

**Comment by tuanna-hsp** [comment]
I noticed that when i run the app, sometimes the monitor reports error logs with DrawableWrapper of some sorts.

**Comment by renaudcerrato** [comment]
I need more informations, paste the some errors reports at least. Does it works with minify disabled?

**Comment by tuanna-hsp** [comment]
In summary:
- No minify: the toggle works, but can not finish animation, like the screenshot above. This happen when being built with some PC only, for some others it works just fine (with a same source code).
  Mine built fine until recently.
- Build release with minify enable: No animation at all, the toggle always showed as hamburger icon.

As for the logs, i will attach when i catch them again :)

**Comment by renaudcerrato** [comment]
Did you tried to build the sample app? Does it works?

**Comment by tuanna-hsp** [comment]
I have not but i will try.

**Comment by tuanna-hsp** [comment]
This is the log
![capture](https://cloud.githubusercontent.com/assets/14136939/13603246/5691d2a0-e56e-11e5-81f2-2e22b8018f35.PNG)

**Comment by ernestkamara** [comment]
Hello @tuanna-hsp,
Are you using wrapping the FloatingSearchView in  an AppBarLayout or a custom Layout in your app above? 
Thanks.

**Comment by tuanna-hsp** [comment]
Yes, im using it with an AppBarLayout

**Comment by ernestkamara** [comment]
Can you please share your layout file with me?

**Comment by tuanna-hsp** [comment]
Problem is that if im using my friend laptop to build, its fine :)
[fragment_home.zip](https://github.com/renaudcerrato/FloatingSearchView/files/169137/fragment_home.zip)

**Comment by tuanna-hsp** [comment]
By the way, im upload some recent crash reports of our app.
![capture](https://cloud.githubusercontent.com/assets/14136939/13703652/17486808-e7ca-11e5-950a-2538018f5abc.PNG)
![capture2](https://cloud.githubusercontent.com/assets/14136939/13703651/17482aaa-e7ca-11e5-84c7-228b373f2d23.PNG)

**Comment by ernestkamara** [comment]
So you do not recommend using this library?

**Comment by renaudcerrato** [comment]
@tuanna-hsp : sounds like a build problem on your side. PLEASE try to build the sample using gradle command line.

**Comment by tuanna-hsp** [comment]
It seems good enough, but as up now maybe the author need some fix up. Im planning to use another one first util next library version.

**Comment by renaudcerrato** [comment]
@ernestkamara : please open an issue regarding your crash report(s).

**Comment by tuanna-hsp** [comment]
@renaudcerrato I built release using commandline, with obfuscating, and the toggle animation is gone completely. Is there any proguard rule?
![screenshot_2016-03-11-20-51-50-418](https://cloud.githubusercontent.com/assets/14136939/13703834/2f6a8320-e7cb-11e5-8d11-782e18ed34f8.jpeg)

**Comment by ernestkamara** [comment]
Sounds more like ProGuard issue @tuanna-hsp.

**Comment by renaudcerrato** [comment]
Agree.
ᐧ

**Comment by ernestkamara** [comment]
I suggest you create an issue on this @tuanna-hsp since you have a better insight on it! I will keep an eye on it and update this thread if i come across it.

**Comment by renaudcerrato** [comment]
@tuanna-hsp : yes, they're rules but they should already be included in the default android proguard: animations works using ObjectAnimators, so you should NOT remove set_/get_ methods! Please disable proguard to confirm.

**Comment by tuanna-hsp** [comment]
I can't disable Proguard because this is the release version of our app. And i think im not removing anything.
[proguard-rules.zip](https://github.com/renaudcerrato/FloatingSearchView/files/169216/proguard-rules.zip)

**Comment by renaudcerrato** [comment]
@tuanna-hsp : I'm just asking to disable Proguard **temporarily** for your tests. Proguard **WILL** remove any "apparently" unused methods as a default. See http://stackoverflow.com/questions/11640977/how-to-use-android-propertyvaluesholder-with-proguard

**Comment by tuanna-hsp** [comment]
- No Proguard, no 'minifyEnable true' : Animation works but can't finish, like the first image in this issue. This depends on which PC the app being built.
- With Proguard, 'minifyEnable false' : No animation.

**Comment by tuanna-hsp** [comment]
And you should provide users with Proguard rule concerning the working of your library, because you know your library than us. 
I will try to investigate the problem when i have time :x

**Comment by renaudcerrato** [comment]
If you're using my [ToggleDrawable](https://github.com/renaudcerrato/ToggleDrawable), [the rules](https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/proguard-rules.pro) should already [be included in your build](https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/build.gradle#L12).

Something is probably going wrong in your build env?

**Comment by tuanna-hsp** [comment]
Ok, i will check again sometime :)

**Comment by danielto** [comment]
Hi, I have the same problem. When using "minifyEnabled true" there is no animation for the DrawerArrowDrawable. 

I am setting the drawer icon like this: 
`searchView.setIcon(new DrawerArrowDrawable(this));`

After adding this rule to proguard, the animation works when focusing FloatingSearchView:
`-keep public class android.support.v7.graphics.** { *; }`

But still does not work when navigation drawer is opening. But as the same behavior is in Google Play app, I suppose it it OK.

**Comment by renaudcerrato** [comment]
@danndi : 

```
-keepclassmembers class * extends com.mypopsy.drawable.ToggleDrawable {
    void setProgress(float);
    float getProgress();
}
```
